#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASS}
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
#    url: jdbc:postgresql://localhost:5432/dbclientes
#    username: postgres
#    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true    


server:
  port: 9090
